[package]
name = "gdm"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bytes = "1.10.1"
clap = "4.5.48"
lazy_static = "1.5.0"
reqwest = { version = "0.12.23", features = ["json"] }
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1.47.1", features = ["full"] }
toml = "0.9.7"
url = "2.5.7"
zip = "5.1.1"

[dev-dependencies]
mockall = "0.13.1"
