[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }

[package]
name = "gdm"
version = "0.1.0"
edition = "2024"
description = "A CLI tool to manage Godot addons"
authors = ["Jani Koponen"]

[dependencies]
anyhow = "1.0.100"
async-channel = "2.5.0"
async-trait = "0.1.89"
bytes = "1.10.1"
cfg-if = "1.0.3"
clap = { version = "4.5.48", features = ["derive"] }
console = "0.16.1"
dotenv = "0.15.0"
futures = "0.3.31"
indicatif = "0.18.0"
lazy_static = "1.5.0"
reqwest = { version = "0.12.23", features = ["json"] }
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
url = "2.5.7"
zip = "5.1.1"

[dev-dependencies]
http = "1.3.1"
mockall = "0.13.1"
mockall_double = "0.3.1"
