name: release
on:
 release:
    types:
    - created

permissions:
  contents: write
  checks: write
  actions: read
  issues: read
  packages: write
  pull-requests: read
  repository-projects: read
  statuses: read

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Install Windows targets
      uses: actions-rust-lang/setup-rust-toolchain@v1
    
    - name: Build the executable
      run: cargo build --release --target x86_64-pc-windows-gnu

    - name: Zip windows binary
      run: Compress-Archive -Path .\\target\\x86_64-pc-windows-gnu\\release\\gdm.exe -DestinationPath gdm-windows.zip

    - name: Generate SHA256 checksums
      run: |
        shasum -a 256 gdm-windows.zip > gdm-windows.zip.sha256
    - name: Upload release binaries
      uses: alexellis/upload-assets@0.4.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["gdm-windows.zip", "gdm-windows.zip.sha256"]'
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    
    - name: Install Linux and Windows Cross Compilers
      run: sudo apt-get update && sudo apt-get install --yes musl-dev musl-tools gcc-mingw-w64-x86-64-win32 libssl-dev

    - name: Install Linux and Windows targets
      uses: actions-rust-lang/setup-rust-toolchain@v1
    
    - name: Build the executable
      run: cargo build --release --target x86_64-unknown-linux-musl

    - name: Tar x86_64 binary
      run: tar -czvf gdm-linux-x86_64.tar.gz -C target/x86_64-unknown-linux-musl/release gdm

    - name: Generate SHA256 checksums
      run: |
        shasum -a 256 gdm-linux-x86_64.tar.gz > gdm-linux-x86_64.tar.gz.sha256
    - name: Upload release binaries
      uses: alexellis/upload-assets@0.4.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["gdm-linux-x86_64.tar.gz", "gdm-linux-x86_64.tar.gz.sha256"]'
  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Install MacOS targets
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Build the executable
      run: cargo build --release --target=x86_64-apple-darwin --target=aarch64-apple-darwin

    - name: Tar x86_64 binary
      run: tar -czvf gdm-macos-x86_64.tar.gz -C target/x86_64-apple-darwin/release gdm

    - name: Tar aarch64 binary
      run: tar -czvf gdm-macos-aarch64.tar.gz -C target/aarch64-apple-darwin/release gdm

    - name: Generate SHA256 checksums
      run: |
        shasum -a 256 gdm-macos-x86_64.tar.gz > gdm-macos-x86_64.tar.gz.sha256
        shasum -a 256 gdm-macos-aarch64.tar.gz > gdm-macos-aarch64.tar.gz.sha256
    - name: Upload release binaries
      uses: alexellis/upload-assets@0.4.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["gdm-macos-x86_64.tar.gz", "gdm-macos-aarch64.tar.gz", "gdm-macos-x86_64.tar.gz.sha256", "gdm-macos-aarch64.tar.gz.sha256"]'